#!/bin/bash

check_src2=0
type=0
connect=0
vgt_dir=/sys/kernel/vgt
filelist=`ls $vgt_dir`
for guest in $filelist
do
	if [ x"${guest:0:2}" != x"vm" ]; then
		continue
	fi

	if [ x"$1" == x"0" ]; then
		src1=/sys/class/drm/card0-eDP-1
		target=$vgt_dir/$guest/PORT_A
		type=1
	elif [ x"$1" == x"1" ]; then
		src1=/sys/class/drm/card0-DP-1
		src2=/sys/class/drm/card0-HDMI-A-1
		target=$vgt_dir/$guest/PORT_B
		check_src2=1
		type=2
	elif [ x"$1" == x"2" ]; then
		src1=/sys/class/drm/card0-DP-2
		src2=/sys/class/drm/card0-HDMI-A-2
		target=$vgt_dir/$guest/PORT_C
		check_src2=1
		type=3
	elif [ x"$1" == x"3" ]; then
		src1=/sys/class/drm/card0-DP-3
		src2=/sys/class/drm/card0-HDMI-A-3
		target=$vgt_dir/$guest/PORT_D
		check_src2=1
		type=4
	elif [ x"$1" == x"4" ]; then
		src1=/sys/class/drm/card0-VGA-1
		target=$vgt_dir/$guest/PORT_E
		type=0
	fi

	if [ ! -d $target ]; then
		continue
	fi

	if [ -d $src1 ] && [ `cat $src1/status` == "connected" ]; then
		dd if=$src1/edid of=$target/edid bs=128 count=1
		echo $type > $target/type
		connect=1
	fi

	if [ -d $src2 ] && [ $check_src2 -eq 1 ] && [ `cat $src2/status` == "connected" ]; then
		dd if=$src2/edid of=$target/edid bs=128 count=1
		type=`expr $type + 3`
		echo $type > $target/type
		connect=1
	fi

	if [ $connect -eq 1 ]; then
		echo "connect" > $target/connection
	else
		echo "disconnect" > $target/connection
	fi

done

