#!/usr/bin/python

import os, sys, re
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-i", "--info", dest="reginfo", action="store_true",
		   help="show info/stat for accessed registers", default=True)
parser.add_option("-r", "--regname", dest="regname", action="store_true",
		   help="show the list of register names")
parser.add_option("-f", "--file", dest="filename", metavar="FILE",
		   default="drivers/xen/vgt_reg.h",
		   help="the location of vgt_reg.h (default drivers/xen/vgt_reg.h)")
parser.add_option("-u", "--untracked", dest="untrack", action="store_true",
		   help="show the list of untracked registers")
parser.add_option("-v", "--verbose", dest="verbose",
		   help="pring status message", action="store_true")

(options, args) = parser.parse_args()
if options.verbose:
	print (options, args)

if options.verbose:
	print "Use %s as the reg file" % options.filename
fi = open(options.filename, "r")
s = fi.read()
fi.close()

# Collect reg name
reginfo = {}
for line in s.split("\n"):
	m = re.search("^#define[ \t]+_REG_[A-Z_]+", line)
	if not m:
		continue
	m = re.search("^#define[ \t]+_REG_(?P<name>[0-9A-Z_]+)[ \t]+(?P<offset>0x[0-9a-zA-Z]+)", line)

	if not m or m.group("name") == "INVALID":
		continue
	offset = int(m.group("offset"), 16)
	if not offset in reginfo:
		reginfo[offset] = {}
		reginfo[offset]["name"] = m.group("name")
	elif reginfo[offset]["name"].find(m.group("name")) == -1:
		reginfo[offset]["name"] += " | " + m.group("name")
		if options.verbose:
			print "find multiple names for regs", hex(offset), reginfo[offset]["name"]
	#print hex(offset), reginfo[offset]["name"]

# get info for each access reg
fi = open("/sys/kernel/debug/vgt/reginfo", "r")
info = fi.read()
fi.close()
for line in info.split("\n"):
	if len(line.split(":")) == 1 or line.find("Reg:") != -1:
		continue
	m = re.search("^[ \t]*(?P<reg>[0-9a-zA-Z]+):[ \t]*(?P<flags>[0-9a-zA-Z]+) ", line)
	if not m:
		continue
	reg = int(m.group("reg"), 16)
	if not reg in reginfo:
		reginfo[reg] = {}
		reginfo[reg]["name"] = ""
	flags = int(m.group("flags"), 16)

	reginfo[reg]["Accessed"] = True
	reginfo[reg]["Owner"] = "N/A"
	if (flags & 0xf == 0):
		reginfo[reg]["Owner"] = "None"
	elif (flags & 0xf == 4):
		reginfo[reg]["Owner"] = "RDR"
	elif (flags & 0xf == 5):
		reginfo[reg]["Owner"] = "DPY"
	elif (flags & 0xf == 6):
		reginfo[reg]["Owner"] = "PM"
	elif (flags & 0xf == 7):
		reginfo[reg]["Owner"] = "MGMT"

	reginfo[reg]["Type"] = "N/A"
	if (flags & 0xf != 0):
		reginfo[reg]["Type"] = "MPT"
	elif (flags & (1 << 12)):
		reginfo[reg]["Type"] = "Boot"
	elif (flags & (1 << 4)):
		reginfo[reg]["Type"] = "WA"
	elif (flags & (1 << 7)):
		reginfo[reg]["Type"] = "Virt"

	if (flags & (1 << 5)):
		reginfo[reg]["AddressFix"] = True;
	if (flags & (1 << 6)):
		reginfo[reg]["HwStatus"] = True;
	if (flags & (1 << 8)):
		reginfo[reg]["ModeMask"] = True;
	if (flags & (1 << 10) == 0):
		reginfo[reg]["Untracked"] = True;
	reginfo[reg]["Flags"] = flags;

def get_reg_attr(reg):
	out = ""
	if "AddressFix" in reg:
		out += " AF"
	if "HwStatus" in reg:
		out += " HW"
	if "ModeMask" in reg:
		out += " MD"
	return out

def get_reg_state(reg):
	out = ""
	if "Untracked" in reg:
		out += " U"
	return out

def show_reginfo():
	print "===================================="
	print "Owner Type:"
	print "\tNone, RDR(Render), DPY(Display), PM, MGMT(Management)"
	print "Type:"
	print "\tVIRT - default virtualized"
	print "\tMPT - Mediated Pass-Through based on owner type"
	print "\tWA - workaround regs pass-through to any VM"
	print "\tBOOT - pass-through to dom0 at boot time. Otherwise virtualized"
	print "Attributes:"
	print "\tAF - Address check required"
	print "\tHW - Contain HW updated status bit"
	print "\tMD - High 16bits as mask for change"
	print "State:"
	print "\tU - Untracked"
	print "\tD - Different value among VMs"

	print "\n%10s: %5s|%5s|%12s|%8s|%-8s" % ("Reg", "Owner", "Type", "Attributes", "State", "Name")
	print "------------------------------------"

	i = 0
	for reg in sorted(reginfo):
		if not "Accessed" in reginfo[reg]:
			continue
		print "%10s: %5s|%5s|%12s|%8s|%s" % (hex(reg), reginfo[reg]["Owner"], reginfo[reg]["Type"], get_reg_attr(reginfo[reg]), get_reg_state(reginfo[reg]), reginfo[reg]["name"])
		i += 1
	print "Total %d registers" % i
	print "===================================="

def show_regname():
	print "=============Reg Name==============="
	print "\"A\": the reg is accessed"
	print "------------------------------------"
	i = 0
	for reg in sorted(reginfo):
		if "Accessed" in reginfo[reg]:
			ac = "A"
		else:
			ac = " "
		print "%10s(%s): %s" % (hex(reg), ac, reginfo[reg]["name"])
		i += 1
	print "Total %d registers" % i
	print "===================================="

def show_untracked():
	print "===========Untracked Regs==========="
	i = 0
	for reg in sorted(reginfo):
		if not "Accessed" in reginfo[reg]:
			continue;

		if "Untracked" in reginfo[reg]:
			print "%10s: %s" %(hex(reg), reginfo[reg]["name"])
			i += 1
	print "Total %d registers" % i
	print "===================================="

if options.regname:
	show_regname()
elif options.untrack:
	show_untracked()
else:
	show_reginfo()
